version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: itachi007
      POSTGRES_PASSWORD: itachi007
      POSTGRES_DB: api_naruto
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/18/docker
volumes:
  database: